apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pubsub-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-pubsub-microservice
  template:
    metadata:
      labels:
        app: go-pubsub-microservice
    spec:
      containers:
      - name: pubsub-microservice
        image: dipjyotimetia/pubsub-emulator:latest
        env:
        - name: PUBSUB_EMULATOR_HOST
          value: "localhost:8432"  
        - name: PUBSUB_PROJECT_ID
          value: "fleet-muse-436011-v4"
        - name: PUBSUB_TOPIC
          value: "topic-1"
        - name: PUBSUB_SUBSCRIPTION
          value: "sub_1,sub_2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-microservice-service
spec:
  selector:
    app: go-pubsub-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
